/* Generated by Together */

package com.hzjc.hz2004.vo;

import com.hzjc.wsstruts.vo.*;
import com.hzjc.hz2004.po.PoXT_SJZDB;

/**
 *
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版
 *                 系统数据字典</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author huhua(hh_hz@126.com)
 * @version 1.0
 */
public class VoXT_SJZDB
    extends DefaultVO {
  public VoXT_SJZDB(PoXT_SJZDB poXt_Sjzdb) {
    super(poXt_Sjzdb);
  }

  //==============VoXT_SJZDB======================
  private long zdid;
  private String zdmc;
  private String zdhy;
  private String zdlx;
  private String zdcd;
  private String zdmj;
  private String bdlx;
  private String bdsj;

  public void setZdid(long zdid) {
    this.zdid = zdid;
  }

  public long getZdid() {
    return zdid;
  }

  public void setZdmc(String zdmc) {
    this.zdmc = zdmc;
  }

  public String getZdmc() {
    return zdmc;
  }

  public void setZdhy(String zdhy) {
    this.zdhy = zdhy;
  }

  public String getZdhy() {
    return zdhy;
  }

  public void setZdlx(String zdlx) {
    this.zdlx = zdlx;
  }

  public String getZdlx() {
    return zdlx;
  }

  public void setZdcd(String zdcd) {
    this.zdcd = zdcd;
  }

  public String getZdcd() {
    return zdcd;
  }

  public void setZdmj(String zdmj) {
    this.zdmj = zdmj;
  }

  public String getZdmj() {
    return zdmj;
  }

  public void setBdlx(String bdlx) {
    this.bdlx = bdlx;
  }

  public String getBdlx() {
    return bdlx;
  }

  public void setBdsj(String bdsj) {
    this.bdsj = bdsj;
  }

  public String getBdsj() {
    return bdsj;
  }
//==================================================================

}
