---------2012-7-27 10:13:46 [省级旅馆业新增加的菜单] mrf-------------
insert into sys_function_info (FUNID, FUNCTION_BM, FUNCTION_NAME, FUNCTION_DESC, FUNCTION_URL, FUNCTION_ORDER, NEW_USER_UID, NEW_DATE, PARENT_PROJECT_BM, PARENT_FUNID, XMBM, ZYLX, CJBM, PXH, ZZCD, SFKJ, DSBM, SFYC)
values ('LGLFRY', 'LGLFRY', '旅馆来访人员', '', 'lg/lglfry.jsp', 6, 'admin', to_date('28-02-2012 11:33:43', 'dd-mm-yyyy hh24:mi:ss'), '', '', 'LGY', '', '', null, '', '', '', '');
insert into sys_function_info (FUNID, FUNCTION_BM, FUNCTION_NAME, FUNCTION_DESC, FUNCTION_URL, FUNCTION_ORDER, NEW_USER_UID, NEW_DATE, PARENT_PROJECT_BM, PARENT_FUNID, XMBM, ZYLX, CJBM, PXH, ZZCD, SFKJ, DSBM, SFYC)
values ('LGCYRY', 'LGCYRY', '旅馆从业人员', '', 'lg/lgcyry.jsp', 7, 'admin', to_date('28-02-2012 11:33:43', 'dd-mm-yyyy hh24:mi:ss'), '', '', 'LGY', '', '', null, '', '', '', '');
commit;
---------2012-7-27 10:13:50 [省级旅馆业新增加的菜单] mrf-------------

