---------2012-7-27 10:13:590 [省级旅馆业新增加的菜单赋予旅馆业管理员的角色] mrf-----------
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c911013515dce80a011c', 'LGLFRY', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c921013515dce80a011c', 'LGCYRY', 'LGYADMIN', 'admin', sysdate, 'LGY');
commit;
---------2012-7-27 10:14:01 [省级旅馆业新增加的菜单赋予旅馆业管理员的角色] mrf-----------