---------2012-3-6 12:04:05 [增加分局管理员的角色的权限] mrf------------
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c7410135e5dce80a001c', 'QXGLYHHF', 'FJGLY', 'admin', sysdate, 'QXGL');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c7410135e5dce80a001d', 'QXGLYHSQ', 'FJGLY', 'admin', sysdate, 'QXGL');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c7410135e5dce80a001e', 'QXGLZZHF', 'FJGLY', 'admin', sysdate, 'QXGL');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c7410135e5dce819001f', 'JGRYGL', 'FJGLY', 'admin', sysdate, 'QXGL');
commit;
---------2012-3-6 12:04:05 [增加分局管理员的角色的权限] mrf------------

---------2012-5-9 13:45:47 [增加旅馆业系统管理员的角色的权限] mrf-----------
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c741013515dce80a011c', 'LGKJ', 'LGYADMIN', 'admin', sysdate, 'LGY');
commit;
---------2012-5-9 13:45:47 [增加旅馆业系统管理员的角色的权限] mrf-----------