/***************************************************************/
/*  Designed for Oracle 10g                                    */
/*  COPYRIGHT  GNT (2012)   WRITER MRF                         */
/***************************************************************/


insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('JGRYGL','JGRYGL','机构人员管理','QXGL',1,'admin',sysdate,'ry/jgrygl.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXGLYHHF','QXGLYHHF','用户恢复','QXGL',1,'admin',sysdate,'ry/ryhf.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXGLZZHF','QXGLZZHF','组织恢复','QXGL',1,'admin',sysdate,'ry/dwhf.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXGLXMGL','QXGLXMGL','项目管理','QXGL',1,'admin',sysdate,'xmgl/xmgl.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXGLXMGLDGL','QXGLXMGLDGL','项目功能点管理','QXGL',1,'admin',sysdate,'xmgl/xmfngl.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXGLJSGL','QXGLJSGL','角色管理','QXGL',1,'admin',sysdate,'sq/jsgl.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXGLYHSQ','QXGLYHSQ','用户授权','QXGL',1,'admin',sysdate,'sq/yhsq.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXGLXTBASJCZ','QXGLXTBASJCZ','XTBA缓存重载','QXGL',1,'admin',sysdate,'');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXGLJCCODECZ','QXGLJCCODECZ','JCCODE重载','QXGL',1,'admin',sysdate,'');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXGLZDCZ','QXGLZDCZ','本地字典重载','QXGL',1,'admin',sysdate,'');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXGLXGMM','QXGLXGMM','修改密码','QXGL',1,'admin',sysdate,'');
commit;


insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('NBZHCX','NBZHCX','内宾组合查询','LGY',1,'admin',sysdate,'nb/nbgazhquery.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('NBYTDCDJCX','NBYTDCDJCX','内宾一天多处登记查询','LGY',1,'admin',sysdate,'nb/nbitdcdj.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('NBPLFX','NBPLFX','内宾频率分析','LGY',1,'admin',sysdate,'nb/nbplfx.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('NBDSDCX','NBDSDCX','内宾多时段查询','LGY',1,'admin',sysdate,'nb/nbdsd.jsp');
       
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('WBZHCX','WBZHCX','外宾组合查询','LGY',1,'admin',sysdate,'wb/wbgazhquery.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('WBYTDCJJCX','WBYTDCJJCX','外宾一天多处登记查询','LGY',1,'admin',sysdate,'wb/wbitdcdj.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('WBPLFX','WBPLFX','外宾频率分析','LGY',1,'admin',sysdate,'wb/wbplfx.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('WBDSDCX','WBDSDCX','外宾多时段查询','LGY',1,'admin',sysdate,'wb/wbdsd.jsp');

insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('KYFBTJ','KYFBTJ','客源分布统计','LGY',1,'admin',sysdate,'tj/lknbfb.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('WBJBQKTJ','WBJBQKTJ','外宾基本情况统计','LGY',1,'admin',sysdate,'tj/wbjbqk.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('WBJDQKTJ','WBJDQKTJ','外宾接待情况统计','LGY',1,'admin',sysdate,'tj/wbjdqk.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('WLRYTJ','WLRYTJ','五类人员统计','LGY',1,'admin',sysdate,'tj/wlrytj.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('RJSYTJ','RJSYTJ','入境事由统计','LGY',1,'admin',sysdate,'tj/rjsytj.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGJBQKTJ','LGJBQKTJ','旅馆基本情况统计','LGY',1,'admin',sysdate,'tj/lgjbqktj.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGXSAJTJ','LGXSAJTJ','旅馆刑事案件统计','LGY',1,'admin',sysdate,'tj/lgxsaj.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGZAAJTJ','LGZAAJTJ','旅馆治安案件统计','LGY',1,'admin',sysdate,'tj/lgzaaj.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGCFJGTJ','LGCFJGTJ','旅馆处罚结果统计','LGY',1,'admin',sysdate,'tj/lgcfjgtj.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGFSTJ','LGFSTJ','旅馆数据发送统计','LGY',1,'admin',sysdate,'tj/lgsjfstj.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('QXSJFSTJ','QXSJFSTJ','区县数据发送统计','LGY',1,'admin',sysdate,'tj/qxsjfstj.jsp');
       
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGXXCX','LGXXCX','旅馆信息查询','LGY',1,'admin',sysdate,'lg/lgxxcx.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGCFGL','LGCFGL','旅馆处罚管理','LGY',1,'admin',sysdate,'lg/lgcfcx.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGFAGL','LGFAGL','旅馆发案管理','LGY',1,'admin',sysdate,'lg/lgfagl.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGFTCX','LGFTCX','旅馆房态查询','LGY',1,'admin',sysdate,'lg/lgftcx.jsp');
       
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('TZGGGL','TZGGGL','通知通告管理','LGY',1,'admin',sysdate,'lg/tztggl.jsp');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('TZGGCX','TZGGCX','通知通告查询','LGY',1,'admin',sysdate,'lg/tztgcx.jsp');

insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGZSFK','LGZSFK','核实旅馆住宿情况','LGY',1,'admin',sysdate,'');
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGYXGMM','LGYXGMM','修改密码','LGY',1,'admin',sysdate,'');
       
insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGYXTRZCX','LGYXTRZCX','系统日志查询','LGY',1,'admin',sysdate,'xtgl/querysysloglist.jsp');

insert into sys_function_info(funid,function_bm,function_name,xmbm,function_order,new_user_uid,new_date,FUNCTION_URL)
values('LGYXGLG','LGYXGLG','旅馆维护','LGY',1,'admin',sysdate,'');

commit;