/***************************************************************/
/*  Designed for Oracle 10g                                    */
/*  COPYRIGHT  GNT (2012)   WRITER MRF                         */
/***************************************************************/


INSERT INTO SYS_PROJECT_INFO(XMBM,XMMC,CJSJ,ZXBZ)VALUES('QXGL','权限管理',sysdate,'0');
INSERT INTO sys_project_info(XMBM,XMMC,CJSJ,ZXBZ)VALUES('LGY','旅馆业',sysdate,'0');
commit;