---------2012-3-6 12:04:05 [增加分局管理员的角色的权限] mrf------------
insert into SYS_FUNCTION_INFO_ROLE
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c7410135e5dce80a001c', 'QXGLYHHF', 'FJGLY', 'admin', sysdate, 'QXGL');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c7410135e5dce80a001d', 'QXGLYHSQ', 'FJGLY', 'admin', sysdate, 'QXGL');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c7410135e5dce80a001e', 'QXGLZZHF', 'FJGLY', 'admin', sysdate, 'QXGL');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c7410135e5dce819001f', 'JGRYGL', 'FJGLY', 'admin', sysdate, 'QXGL');
commit;
---------2012-3-6 12:04:05 [增加分局管理员的角色的权限] mrf------------

---------2012-5-9 13:45:47 [增加旅馆业系统管理员的角色的权限] mrf-----------
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c741013515dce80a011c', 'LGKJ', 'LGYADMIN', 'admin', sysdate, 'LGY');
commit;
---------2012-5-9 13:45:47 [增加旅馆业系统管理员的角色的权限] mrf-----------

---------2012-7-3 16:39:20 [省级旅馆业新增加的菜单赋予旅馆业管理员的角色] mrf-----------
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c711013515dce80a011c', 'LGLTLTJ', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c721013515dce80a011c', 'LGRZLTJ', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c731013515dce80a011c', 'SCYCLG', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c741113515dce80a011c', 'LGGWDQSZ', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c751013515dce80a011c', 'LGGWDQTJ', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c761013515dce80a011c', 'LGCQBF', 'LGYADMIN', 'admin', sysdate, 'LGY');
  

insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c821013515dce80a011c', 'LGZHRYTJ', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c831013515dce80a011c', 'LGYBKRYGL', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c841013515dce80a011c', 'LGYBKJGCX', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c851013515dce80a011c', 'LKWJSTFTJ', 'LGYADMIN', 'admin', sysdate, 'LGY');

insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c861013515dce80a011c', 'LGZHRY', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c871013515dce80a011c', 'XTRZTJ', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c881013515dce80a011c', 'MJZAJC', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c891013515dce80a011c', 'LGJFJC', 'LGYADMIN', 'admin', sysdate, 'LGY');
insert into sys_function_info_role
  (gxid, function_bm, role_bm, new_user_id, new_date, xmbm)
values
  ('4028809d35e5c901013515dce80a011c', 'DSRWZXQK', 'LGYADMIN', 'admin', sysdate, 'LGY');
commit;
---------2012-7-3 16:39:20 [省级旅馆业新增加的菜单赋予旅馆业管理员的角色] mrf-----------