/* Generated by Together */

package com.hzjc.wsstruts.common.config;

/**
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2002</p>
 * <p>Company: </p>
 * <p>Note: Add lines at web.xml as follows:
 *     <context-param>
 *       <param-name>homeDir</param-name>
 *       <param-value>/usr/local/tomcat/webapps/fundsite/WEB-INF/homeDir</param-value>
 *     </context-param>
 * </p>
 * @author Kansanku(kgb_hz@126.com)
 * @version 1.0
 */

import java.util.Properties;
import java.io.FileInputStream;
import java.io.File;
import java.io.FileOutputStream;
import org.apache.commons.logging.*;

public class Config {
  private static String configDir = null;
  private static String ZFBA_CONFIG_FILENAME = "/hz2004.properties";
  private static Properties properties = null;

  /*
    static {
      loadProperties();
    }
   */

  private Config() {};

  /**
   * Load properties from czrk.properties
   */
  private synchronized static void loadProperties() {
    try {
      //Open the props file
      Config cfg = new Config();
      //String configDir = cfg.getClass().getResource(CZRK_CONFIG_FILENAME).getPath().substring(1);
      String configDir = cfg.getClass().getResource(ZFBA_CONFIG_FILENAME).
          getPath();
      //Logger.println(configDir);
      File propsFile = new File(configDir);
      properties = new Properties();
      //Read in the stored properties
      properties.load(new FileInputStream(propsFile));
    }
    catch (Exception e) {
      System.err.println("读取zfba.properties失败！请进行系统配置！");
      properties = null;
      e.printStackTrace();
    }
  }

  /**
   *Save properties
   * @param props
   */
  private static void saveProperties(Properties props) {

    //Save the properties defined in props to a disk file
    try {

      File propsFile = new File(configDir);
      propsFile.createNewFile();
      props.store(new FileOutputStream(propsFile), demoData);
    }
    catch (Exception e) {
      e.printStackTrace();
    }
  }

  /**
   *
   * @param key
   * @return
   */
  public static String getProperty(String key) {
    if (properties == null) {
      loadProperties();
    }
    return properties.getProperty(key);
  }

  /**
   *
   * @param key
   * @param defaultValue
   * @return
   */
  public static String getProperty(String key, String defaultValue) {
    if (properties == null) {
      loadProperties();
    }
    return properties.getProperty(key, defaultValue);
  }

  /**
   * Should be deprecated
   * @param key
   * @param value
   */
  public static void setProperty(String key, String value) {
    if (properties == null) {
      loadProperties();
    }
    properties.setProperty(key, value);
    saveProperties(properties);
  }

  public static void main(String[] args) {
    /*
         setProperty("JDBC Driver", "oracle.jdbc.driver.OracleDriver");
         setProperty("Property1", "New Value for Property1");
         setProperty("Property2", "New Value for Property2");
         setProperty("Property3", "New Value for Property3");
         //Output the list to the console
         System.out.println("Properties after update:");
         System.out.println(getProperty("JDBC Driver"));
         System.out.println(getProperty("Property1"));
         System.out.println(getProperty("Property2"));
         System.out.println(getProperty("Property3"));
     */
    //Save the updated properties list to the props file
    //saveProperties(props);
    System.out.println(Config.getHomeDir());
  }

  /**
   *
   * @return
   */
  public static String getHomeDir() {
    if (properties == null) {
      loadProperties();
    }
    return configDir;
  }

  private static final String demoData =
      "##########################################################\n" +
      "#CZRK Config File\n" +
      "##########################################################\n\n" +
      "#==============================================================\n" +
      "#DEMO CONFIGS\n\n" +
      "##################################################\n" +
      "# Home Dir\n" +
      "##################################################\n" +
      "#homeDir=d:/czrkhome\n\n" +
      "##################################################\n" +
      "#USING JNDI\n" +
      "##################################################\n" +
      "#jndiName=oracle_jdbc_pool\n\n" +
      "#Or, Tell system to load JDBC driver directly\n\n" +
      "##################################################\n" +
      "#USING ORACLE JDBC DRIVER\n" +
      "##################################################\n" +
      "#jdbcDriver=oracle.jdbc.driver.OracleDriver\n" +
      "#jdbcUrl=jdbc:oracle:thin:@218.108.37.115:1521:yzttest\n" +
      "#username=sitedb\n" +
      "#password=1234\n" +
      "#maxConn=50\n\n" +
      "##################################################\n" +
      "#USING MYSQL JDBC DRIVER\n" +
      "##################################################\n" +
      "#jdbcDriver=org.gjt.mm.mysql.Driver\n" +
      "#jdbcUrl=jdbc:mysql://localhost:3306/cxweb\n" +
      "#username=root\n" +
      "#password=secret\n\n" +
      "##################################################\n" +
      "#INDEX SETTING\n" +
      "##################################################\n" +
      "#enableSearch=true\n" +
      "#enableAutoIndex=true\n" +
      "#autoIndexInterval=1\n" +
      "#lastUpdate=1045032215179\n\n" +
      "#DEMO CONFIG END\n" +
      "#========================================================\n\n\n" +
      "#========================================================\n" +
      "#Real Config Data\n" +
      "#========================================================\n";
}
