/* Generated by Together */

package com.hzjc.wsstruts.po;

import java.io.Serializable;

/**
 * 实体接口
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author Kansan Ku(kgb_hz@126.com)
 * @version 1.0
 */
public interface PO
    //extends Serializable
    {
}
