/* Generated by Together */

package com.hzjc.wsstruts.po;

/**
 * 实体接口的默认实现
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author Kansan Ku(kgb_hz@126.com)
 * @version 1.0
 */
abstract public class DefaultPO
    implements PO {
}
