/***************************************************************/
/*  Designed for Oracle 10g                                    */
/*  COPYRIGHT  GNT (2012)   WRITER MRF                         */
/***************************************************************/


insert into SYS_PROJECT_FL(flid,flname,xmlb) values('QXGL','权限管理系统','QXGL');
insert into sys_project_fl(flid,flname,xmlb) values('LGY','旅馆业系统','LGY');
commit;